terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  .//tmp_files/7600.sh: line 3: 228795 Aborted                 speed3d_r2c fftw float-long 1400 1400 1400 -no-reorder -a2a -r2c_dir 1 -no-gpu-aware -n5
[NID 01245] 2023-07-21 07:29:12 Apid 28477885: initiated application termination
std::bad_alloc
.//tmp_files/7600.sh: line 3: 19225 Aborted                 speed3d_r2c fftw float-long 1400 1400 1400 -no-reorder -a2a -r2c_dir 1 -no-gpu-aware -n5
[NID 00968] 2023-07-21 07:29:20 Apid 28477885: Error detected during page fault processing.  Process terminated via bus error.
[NID 01240] 2023-07-21 07:29:20 Apid 28477885: Error detected during page fault processing.  Process terminated via bus error.
